### ISSUE TITLE
stacktrace

### ISSUE THREAD

**Issue by davidhq** [jokeyrhyme/tape-chai.js#1]
Hi, great library - thank you...

I have two comments though:

When I get this failure:

    ✖ lengthOf
    -----------
      operator: equal
      expected: 3
      actual:   2
      at: Test.lengthOf (/Users/david/Projects/node/avantgo/node_modules/tape-chai/index.js:188:10)

The `at` part is not very helpful.. I'd like to see the exact line in my tests where assert fails..

is this somehow possible?

thank you
david

**Comment by jokeyrhyme** [comment]
Yeah, I definitely haven't worked on the finer points of stack traces and helpful error messages yet.

At this point, I'm transitioning my own projects away from chai, to use https://github.com/power-assert-js/power-assert instead. Test frameworks like https://github.com/sindresorhus/ava automatically wire it up for you, and the failure output is incredibly helpful.

**Comment by davidhq** [comment]
Thank you for the hints.. So you are also abandoning Tape? What is the biggest advantage of Ava? I tried it but it has so many dependencies that I was turned away from it... it takes a lot of time to install.

Is `power-assert` also useful with Tape? I tried it now but tape doesn't count asserts done by `power-assert` so it says `0 tests run`.. and if such assert test fails, the output is not useful at all... 

So again: does `power-assert` plug into ava much better than into tape (is it possible here at all)? And what other things are better in Ava (just quickly mention please) in comparison to Tape.

Thank you very much.

**Comment by jokeyrhyme** [comment]
ava isn't really useful for browser tests yet, but it's great for Node.js testing.

For me, the main upside for ava is that is automatically sets up babel and power-assert for your tests. So you don't need to worry about figuring out the build steps necessary. It's all automatic.

You can probably use power-assert with tape, but you'll need to just use `t.ok()` and write all your assertions as expressions that end up truthy or falsey. And you'd still need to add the espower build step for maximum advantage. I'd just switch from tape to ava, way easier. :)

**Comment by davidhq** [comment]
Great info, thank you... but let's first make something clear: how easy is it to fix `tape-chai` to give sensical line numbers for failling tests? I feel like it may be worth it even if I never actually use it on another project... I tried to fix this before but at least in my view it's not easy unless I'd know a special trick.. I also saw that you had to reimplement all chai assert clauses by hand... I tried to print the stack with 

```
console.trace("Here I am!")
```

and 

```
var stack = new Error().stack
console.log(stack)
```

and I get info I want in 3rd line:

```
Trace: Here I am!
    at Test.lengthOf (/Users/david/Projects/node/avantgo/node_modules/tape-chai/index.js:187:9)
    at Test.bound [as lengthOf] (/Users/david/Projects/node/avantgo/node_modules/tape/lib/test.js:61:32)
    at Test.<anonymous> (/Users/david/Projects/node/avantgo/tests/extras.js:64:5)
    ...
```

I'd probably had to amend `this.equal`, `this.instanceOf`, `this.ok` but the trick now is that these are on tape's Test object prototype, so not easy to patch...

What do you say, is it worth it? Do you see an easy solution?

**Comment by jokeyrhyme** [comment]
We could probably use https://www.npmjs.com/package/stack-utils , maybe. Or https://www.npmjs.com/package/stacktrace-js .

I believe I've caused this problem by implementing Chai's API by using the existing tape assertions. So these new assertions add more calls to the stack.

One approach could be to determine how many extra calls each of my new functions adds to the stack. Then for each one, simply remove those calls from the stack trace before outputting it. /shrug

It'd be better to somehow detect this on the fly, so a manual mapping wasn't required, and maybe this can be determined by scanning the stack trace. /shrug

**Comment by sirudog** [comment]
Just a hint:
The developer of tape-expect already did this. Maybe it is worth to check how?
He emphasizes it was not trivial:
https://www.npmjs.com/package/tape-expect#misc
